import Link from "next/link";
import { notFound } from "next/navigation";
import { loadLeaguePortal } from "@/lib/hoops/leagues";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function LeaguePortalPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ division?: string; season?: string }> }) {
  const [{ slug }, query] = await Promise.all([params, searchParams]);
  const portal = await loadLeaguePortal(slug);
  if (!portal) notFound();

  const divisions = Array.from(new Set(portal.memberships.map((item) => item.division))).sort();
  const seasons = Array.from(new Set(portal.memberships.map((item) => item.season_label))).sort().reverse();
  const division = query.division && divisions.includes(query.division) ? query.division : divisions[0] || "";
  const season = query.season && seasons.includes(query.season) ? query.season : seasons[0] || "";
  const standings = portal.standings.filter((row) => (!division || row.division === division) && (!season || row.seasonLabel === season));
  const memberships = portal.memberships.filter((row) => (!division || row.division === division) && (!season || row.season_label === season));
  const primary = safeColor(portal.league.primary_color, "#0B1F3A");
  const secondary = safeColor(portal.league.secondary_color, "#F58220");

  const href = (nextDivision: string, nextSeason = season) => `/leagues/${portal.league.slug}?division=${encodeURIComponent(nextDivision)}&season=${encodeURIComponent(nextSeason)}`;

  return <main className="min-h-screen bg-slate-950 text-white">
    <section className="relative min-h-[470px] overflow-hidden border-b border-white/10">{portal.league.cover_image_url ? <img src={portal.league.cover_image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-40"/> : null}<div className="absolute inset-0" style={{ background: `linear-gradient(110deg,${primary}f5 10%,${primary}dd 55%,${secondary}99)` }}/><div className="relative mx-auto flex min-h-[470px] max-w-7xl flex-col justify-between px-5 py-9 sm:px-6 lg:px-8"><Link href="/leagues" className="w-fit rounded-xl border border-white/20 bg-black/20 px-4 py-2.5 text-[9px] font-black uppercase">← All leagues</Link><div className="flex flex-col gap-5 sm:flex-row sm:items-end">{portal.league.logo_url ? <img src={portal.league.logo_url} alt="" className="h-24 w-24 rounded-3xl border border-white/25 bg-white object-contain p-2 shadow-2xl sm:h-32 sm:w-32"/> : <span className="grid h-24 w-24 place-items-center rounded-3xl border border-white/25 bg-black/20 text-3xl font-black sm:h-32 sm:w-32">{portal.league.short_name || portal.league.name.slice(0,3)}</span>}<div><p className="text-[10px] font-black uppercase tracking-[.2em] text-white/65">League portal · {portal.league.country}</p><h1 className="mt-3 max-w-5xl text-5xl font-black uppercase leading-[.9] sm:text-7xl">{portal.league.name}</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/75">{portal.league.description}</p></div></div></div></section>

    <section className="border-b border-white/10 bg-[#07162b]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-5 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div className="flex gap-2 overflow-x-auto">{divisions.map((item) => <Link key={item} href={href(item)} className={`shrink-0 rounded-xl px-4 py-2.5 text-[9px] font-black uppercase ${item === division ? "text-white" : "border border-white/10 bg-white/[.03] text-zinc-400"}`} style={item === division ? { backgroundColor: secondary } : undefined}>{item}</Link>)}</div>{seasons.length ? <div className="flex gap-2 overflow-x-auto">{seasons.map((item) => <Link key={item} href={href(division, item)} className={`shrink-0 rounded-lg px-3 py-2 text-[8px] font-black uppercase ${item === season ? "bg-white text-slate-950" : "border border-white/10 text-zinc-500"}`}>{item}</Link>)}</div> : null}</div></section>

    <section id="standings" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-12 sm:px-6 lg:px-8 lg:py-16"><p className="text-[10px] font-black uppercase tracking-[.2em]" style={{ color: secondary }}>League intelligence</p><h2 className="mt-2 text-3xl font-black uppercase sm:text-5xl">{division || "Current"} standings</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">Final basketball results produce wins and losses only. Equal scores are excluded until overtime produces a winner.</p>
      {standings.length ? <div className="mt-7 overflow-x-auto rounded-3xl border border-white/10 bg-[#07162b]"><table className="w-full min-w-[820px] text-left"><thead className="border-b border-white/10 bg-black/20 text-[9px] font-black uppercase tracking-[.1em] text-zinc-500"><tr><th className="px-5 py-4">#</th><th className="px-5 py-4">Team</th><th className="px-3 py-4">P</th><th className="px-3 py-4">W</th><th className="px-3 py-4">L</th><th className="px-3 py-4">PF</th><th className="px-3 py-4">PA</th><th className="px-3 py-4">+/-</th><th className="px-3 py-4">Win %</th></tr></thead><tbody>{standings.map((row, index) => <tr key={row.membershipId} className="border-b border-white/[.06]"><td className="px-5 py-4 text-xl font-black text-zinc-500">{index + 1}</td><td className="px-5 py-4"><Link href={`/teams/${row.team.slug}`} className="flex items-center gap-3">{row.team.logo_url ? <img src={row.team.logo_url} alt="" className="h-10 w-10 rounded-xl bg-white object-contain p-1"/> : <span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-xs font-black">{(row.team.short_name || row.team.name).slice(0,2)}</span>}<span><span className="block font-black">{row.team.name}</span><span className="mt-1 block text-[8px] font-bold uppercase text-zinc-600">{row.team.verification_status || "team"}</span></span></Link></td><td className="px-3 py-4 font-black">{row.played}</td><td className="px-3 py-4 font-black text-emerald-300">{row.wins}</td><td className="px-3 py-4 font-black text-red-300">{row.losses}</td><td className="px-3 py-4">{row.pointsFor}</td><td className="px-3 py-4">{row.pointsAgainst}</td><td className="px-3 py-4 font-black">{row.pointDifference > 0 ? "+" : ""}{row.pointDifference}</td><td className="px-3 py-4 font-black">{row.winPercentage.toFixed(1)}%</td></tr>)}</tbody></table></div> : <div className="mt-7 rounded-3xl border border-dashed border-white/15 p-10 text-center text-zinc-500">No teams have been placed in this division and season yet.</div>}
    </section>

    <section className="border-t border-white/10 bg-[#07162b]/85"><div className="mx-auto max-w-7xl px-5 py-12 sm:px-6 lg:px-8"><p className="text-[10px] font-black uppercase tracking-[.2em]" style={{ color: secondary }}>Clubs</p><h2 className="mt-2 text-3xl font-black uppercase">Teams in this table</h2>{memberships.length ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{memberships.map((membership) => <Link key={membership.id} href={`/teams/${membership.team.slug}`} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-black/25 p-4 transition hover:border-white/30">{membership.team.logo_url ? <img src={membership.team.logo_url} alt="" className="h-16 w-16 rounded-2xl bg-white object-contain p-1"/> : <span className="grid h-16 w-16 place-items-center rounded-2xl bg-white/10 text-lg font-black">{(membership.team.short_name || membership.team.name).slice(0,2)}</span>}<span><span className="block text-lg font-black uppercase">{membership.team.name}</span><span className="mt-2 block text-[8px] font-black uppercase text-zinc-500">{membership.division} · {membership.status}</span></span></Link>)}</div> : null}</div></section>
  </main>;
}

function safeColor(value: string | null | undefined, fallback: string) { return /^#[0-9a-f]{6}$/i.test(String(value || "")) ? String(value) : fallback; }
